### ISSUE TITLE
No way to enable the two-step verification

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.googleauthenticator#8]
![screenshot-2018-4-2 site](https://user-images.githubusercontent.com/341393/38208282-eccf79b4-3686-11e8-92cb-5b9e9d64e66e.png)

**Comment by hvelarde** [comment]
@barseghyanartur this seems a regression to me.

**Comment by barseghyanartur** [comment]
@hvelarde:

This is really strange. It should not be that way. This is how it shall work.

http://pythonhosted.org/collective.googleauthenticator/#usage

**Comment by hvelarde** [comment]
@barseghyanartur do you mind to give a look using current buildout? seems some changes on Plone have broke it.

**Comment by barseghyanartur** [comment]
@hvelarde:

Unfortunately, I don't have time for it (and I don't think I will ever). Plone is dying. Companies move towards other (better supported) platforms. Number of professional Plone developers shrinks, which means it's the end. With no developers spending their full time hours time on Plone, its fate is lethal.

**Comment by hvelarde** [comment]
I'll take care of this by myself; thanks anyway!
